[package]
name = "angry-engine-clean"
version = "0.1.0"
description = "ANGRY Engine Clean - Core Engine"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "angry_engine_clean"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
